name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: distribution/windows/release.ps1

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "c:/output/excel2csv.zip"
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}



